#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export MODEL_PATH=${MODEL_PATH:-Qwen/Qwen2.5-VL-3B-Instruct}
export DATA_FORMAT=${DATA_FORMAT:-jsonl}
export TASK_INDICES=${TASK_INDICES:-0}
export EPISODES_PER_TASK=${EPISODES_PER_TASK:-1}
export AGENT_LOOP_CONFIG=${AGENT_LOOP_CONFIG:-$ROOT/configs/envmine_agent_loop_smoke.yaml}

export NNODES=${NNODES:-1}
export NGPUS_PER_NODE=${NGPUS_PER_NODE:-1}
export TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-1}
export PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE:-1}
export MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH:-2048}
export MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-1024}
export PPO_MAX_TOKEN_LEN_PER_GPU=${PPO_MAX_TOKEN_LEN_PER_GPU:-4096}
export ROLLOUT_MAX_MODEL_LEN=${ROLLOUT_MAX_MODEL_LEN:-4096}
export ROLLOUT_TP=${ROLLOUT_TP:-1}
export ROLLOUT_N=${ROLLOUT_N:-1}
export AGENT_LOOP_WORKERS=${AGENT_LOOP_WORKERS:-1}
export ROLLOUT_GPU_MEM_UTIL=${ROLLOUT_GPU_MEM_UTIL:-0.75}
export ROLLOUT_MAX_NUM_SEQS=${ROLLOUT_MAX_NUM_SEQS:-4}
export ROLLOUT_MAX_NUM_BATCHED_TOKENS=${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-4096}
export TOTAL_EPOCHS=${TOTAL_EPOCHS:-1}
export SAVE_FREQ=${SAVE_FREQ:-100}
export TEST_FREQ=${TEST_FREQ:--1}
export EXPERIMENT_NAME=${EXPERIMENT_NAME:-qwen25vl_envmine_grpo_smoke}
export LOGGER=${LOGGER:-'["console"]'}

exec bash "$ROOT/scripts/run_envmine_grpo.sh" "$@"