# Scene: elevator_wood_lodge_green
# Auto-generated by multiagent/scene/generate_scenes.py
# Notes: Warm wooden lodge room: spruce floor, green terracotta walls, copper elevator door, spruce pressure plate.
fill 21 -59 0 35 -59 16 minecraft:spruce_planks
fill 21 -58 0 35 -54 16 minecraft:green_terracotta
fill 22 -58 1 34 -54 15 minecraft:air
fill 21 -53 0 35 -53 16 minecraft:stripped_spruce_wood
fill 22 -53 1 34 -53 1 minecraft:glowstone
fill 22 -53 15 34 -53 15 minecraft:glowstone
fill 22 -53 2 22 -53 14 minecraft:glowstone
fill 34 -53 2 34 -53 14 minecraft:glowstone
fill 22 -58 8 34 -54 8 minecraft:mossy_cobblestone
fill 27 -58 8 29 -56 8 minecraft:copper_block
setblock 28 -59 5 minecraft:spruce_planks
setblock 28 -58 5 minecraft:spruce_pressure_plate

# Command blocks that keep the elevator door open while the plate is pressed.
function multiagent_scene:elevator_wood_lodge_green/place_command_blocks
